### ISSUE TITLE
Problem with edge attribute.

### ISSUE THREAD

**Issue by Bring633** [yascho/interception_smoothing#1]
Hi there,

I encountered a problem when i try to run demo.py.

it says that "'GATConv' object has no attribute '_edge_user_args'" as shown in the figure.

![Screen Shot 2023-09-28 at 16 57 18](https://github.com/yascho/interception_smoothing/assets/89834755/3959ce7c-5d54-4bcc-8f1c-bc6e6447c661)

so, i try to debug it. Then i found that when initialize the Data object, the code did not pass the 'edge_attr' in line 70 in 'demo.py' , which resulting 'NoneType'  (in line 31) when calling the function 'smoothed_gnn' in file 'prediction.py'.

so i would like to ask whether it is ok to not to pass the 'edge_attr' in 'demo.py'. if so, how do i fix it?

Thank you!!!!!!

**Comment by yascho** [comment]
Hi,

the problem starts when loading the model with a newer pyg version. You have two options to fix this
- Instead of loading the pretrained model, train the model by yourself (uncomment the corresponding lines in the notebook)
- Install `pyg 2.0.4` (see README).

Hope it helps

**Comment by Bring633** [comment]
Hi,

Thanks for your reply. I have solve the problem! 

Many many thanks.
